name: Build Tweak

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: theos/theos-docker:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Package
      run: make package SCHEME=rootless

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DYYY-Tweak-Package
        path: packages/*.deb