name: Build Tweak

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Theos
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl perl build-essential xz-utils
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Download Toolchain and SDK
      run: |
        # Download and install the iOS Toolchain
        curl -LO https://github.com/CRKatri/llvm-project/releases/download/18.1.5-1/llvm-project-18.1.5-1-linux.tar.xz
        sudo tar -xf llvm-project-18.1.5-1-linux.tar.xz -C /
        rm llvm-project-18.1.5-1-linux.tar.xz

        # Download and install the iOS 16.1 SDK
        if [ ! -d "$HOME/theos/sdks" ]; then
            mkdir -p $HOME/theos/sdks
        fi
        curl -LO https://github.com/xybp888/iOS-SDKs/releases/download/iOS-SDKs/iPhoneOS16.1.sdk.zip
        unzip iPhoneOS16.1.sdk.zip -d $HOME/theos/sdks/
        rm iPhoneOS16.1.sdk.zip

    - name: Build Package
      run: make package SCHEME=rootless

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DYYY-Tweak-Package
        path: packages/*.deb