name: Build Theos Tweak

on:
  push:
    branches:
      - main
      - 'feature/**' # 当推送到 main 分支或任何 feature 分支时触发
  pull_request:
    branches:
      - main
      - 'feature/**' # 当向 main 分支或 feature 分支提交 PR 时触发
  workflow_dispatch: # 允许手动触发此工作流

jobs:
  build:
    runs_on: ubuntu-latest # 使用最新的 Ubuntu 运行器

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # 检出您的仓库代码

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential fakeroot dpkg perl lzma lzop

      - name: Clone Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git "$HOME/theos"
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV # 设置 THEOS 环境变量

      - name: Download iOS 16.1 SDK
        run: |
          mkdir -p "$HOME/theos/sdks"
          curl -L -o iPhoneOS16.1.sdk.zip https://github.com/xybp888/iOS-SDKs/releases/download/iOS-SDKs/iPhoneOS16.1.sdk.zip
          unzip iPhoneOS16.1.sdk.zip -d "$HOME/theos/sdks/"
          rm iPhoneOS16.1.sdk.zip
          echo "THEOS_SDK_PATH=$HOME/theos/sdks" >> $GITHUB_ENV # 设置 THEOS_SDK_PATH 环境变量

      - name: List Theos Projects (Optional)
        run: ls -F # 列出当前目录内容，确认项目文件夹

      - name: Build and Package Tweak (MyNewDylibTweak)
        # 假设您的 Theos 项目文件夹在 Lemon 仓库的根目录下，名为 MyNewDylibTweak
        # 如果您的项目文件夹不在根目录，例如在 Lemon/tweak 里面，您需要修改 'cd' 命令
        working-directory: ./MyNewDylibTweak # 进入您的 Theos 项目目录
        run: |
          export THEOS=$HOME/theos # 再次确保环境变量设置
          export THEOS_SDK_PATH=$HOME/theos/sdks
          make clean
          make package

      - name: Upload .deb Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyNewDylibTweak-deb
          path: ./MyNewDylibTweak/packages/*.deb # 假设 .deb 在项目目录下的 packages 文件夹中
          if-no-files-found: error # 如果没有找到文件，则报错