name: Build Tweak

on:
  push:
    branches: [ "main", "master" ] # master is a common default branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Install Dependencies
        run: |
          brew install ldid

      - name: Build Package
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DYYY-Tweak-Package
          path: packages/*.deb