# 工作流名称
name: Build Tweak

# 触发工作流的事件
on:
  # 当向指定分支推送代码时触发
  push:
    branches:
      - 'feature/toggleable-search-ui-removal' # 监控你正在开发的分支
      - main # 也监控 main 分支

  # 允许在 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:

# 定义工作任务
jobs:
  build:
    runs-on: ubuntu-latest

    # 工作步骤
    steps:
      # 第一步：检出你的仓库代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 第二步：安装基础依赖环境
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y git build-essential curl

      # 第三步：使用官方脚本安装 Theos, 工具链和 SDK (全新的一体化步骤)
      - name: Install Theos, Toolchain & SDK
        run: |
          # 设置 Theos 安装路径的环境变量
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          # 使用官方脚本自动安装 Theos 和最新工具链
          bash -c "$(curl -fsSL https://get.theos.dev)"
          
      # 第四步：编译和打包 Tweak
      - name: Build and Package Tweak
        run: |
          # 确保 Theos 环境变量在后续步骤中可用
          export THEOS=$HOME/theos
          make clean
          make package

      # 第五步：上传编译好的 .deb 文件作为产物
      - name: Upload .deb Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lemon-Tweak-deb
          path: ./packages/*.deb
          if-no-files-found: error
