name: Build Tweak

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Theos
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl perl build-essential xz-utils
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Download and Verify iOS 16.2 SDK
      run: |
        set -x
        if [ ! -d "$HOME/theos/sdks" ]; then
            mkdir -p $HOME/theos/sdks
        fi
        wget https://sdks.akestic.com/iPhoneOS16.2.sdk.zip
        if ! file iPhoneOS16.2.sdk.zip | grep -q "Zip archive data"; then
            echo "Error: Downloaded file is not a valid zip archive."
            exit 1
        fi
        unzip -o iPhoneOS16.2.sdk.zip -d $HOME/theos/sdks/
        rm iPhoneOS16.2.sdk.zip

    - name: Build Package
      run: make package SCHEME=rootless

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DYYY-Tweak-Package
        path: packages/*.deb