# =======================
#  GitHub Actions 完整工作流：Build Tweak
#  作用：自动编译并打包 iOS 越狱 Tweak
# =======================

name: Build Tweak

on:
  # 监控 main 分支推送
  push:
    branches:
      - main
  # 监控 PR
  pull_request:
  # 允许在 Actions 页面手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Theos 安装路径
      THEOS: ${{ github.workspace }}/theos

    steps:
      # 1️⃣ 检出仓库源码
      - name: Checkout Source
        uses: actions/checkout@v4

      # 2️⃣ 安装编译环境依赖
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            perl \
            fakeroot \
            dpkg \
            ldid \
            clang \
            unzip \
            curl \
            lzma

      # 3️⃣ 安装 Theos
      - name: Setup Theos
        run: |
          mkdir -p "$THEOS/toolchain/linux"
          # 克隆 Theos 主仓库
          git clone --depth=1 https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/theos/theos.git "$THEOS"
          # 克隆 Linux 交叉编译工具链
          git clone --depth=1 https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/theos/toolchain-linux.git "$THEOS/toolchain/linux/iphone"

      # 4️⃣ 下载并安装 iOS 16.1 SDK
      - name: Download iOS 16.1 SDK
        run: |
          mkdir -p "$THEOS/sdks"
          curl -L -o iPhoneOS16.1.sdk.zip \
            https://github.com/xybp888/iOS-SDKs/releases/download/iOS-SDKs/iPhoneOS16.1.sdk.zip
          unzip -o iPhoneOS16.1.sdk.zip -d "$THEOS/sdks/"
          rm iPhoneOS16.1.sdk.zip

      # 5️⃣ 清理并构建 .deb 包
      - name: Build and Package Tweak
        run: |
          make clean
          make package FINALPACKAGE=1

      # 6️⃣ 上传生成的 .deb 文件
      - name: Upload .deb Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lemon-Tweak-deb
          path: ./packages/*.deb
          if-no-files-found: error