# ===================================================================
#
#          最终推荐的 Tweak 自动编译工作流
#          特点：简洁、稳定、官方推荐、带诊断功能
#
# ===================================================================

# 工作流名称
name: Build Tweak

on:
  # 当代码被推送到 main 分支时触发
  push:
    branches:
      - main
  # 允许在 GitHub Actions 页面手动触发
  workflow_dispatch:

jobs:
  build-and-package:
    # 任务名称
    name: Compile and Package .deb

    # 运行环境
    runs-on: ubuntu-latest

    # 任务步骤
    steps:
      # -------------------------------------------------------------------
      # 步骤 1: 检出您的项目代码
      # -------------------------------------------------------------------
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      # -------------------------------------------------------------------
      # 步骤 2: (诊断步骤) 检查关键文件是否存在且内容正确
      # 描述: 这一步会打印出 Makefile 的内容，确保我们使用的是正确版本。
      # -------------------------------------------------------------------
      - name: 2. [Debug] Verify Project Files
        run: |
          echo "--- Verifying Makefile content ---"
          if [ -f "Makefile" ]; then
            cat Makefile
          else
            echo "错误：找不到 Makefile 文件！"
            exit 1
          fi
          echo "------------------------------------"

      # -------------------------------------------------------------------
      # 步骤 3: 安装 Theos 完整编译环境
      # 描述: 使用 Theos 官方一键安装脚本，自动安装所有依赖。
      # -------------------------------------------------------------------
      - name: 3. Install Theos Environment
        run: |
          # 安装基础依赖
          sudo apt-get update
          sudo apt-get install -y git build-essential curl
          # 执行官方安装脚本
          bash -c "$(curl -fsSL https://get.theos.dev)"

      # -------------------------------------------------------------------
      # 步骤 4: 编译并打包 Tweak
      # 描述: 执行 make 命令来编译项目。
      # -------------------------------------------------------------------
      - name: 4. Build and Package Tweak
        run: |
          # 必须在这里导出 THEOS 环境变量，make 命令才能找到它
          export THEOS=$HOME/theos
          make package

      # -------------------------------------------------------------------
      # 步骤 5: 上传编译好的 .deb 文件
      # 描述: 将生成的 .deb 文件作为产物上传，方便您下载。
      # -------------------------------------------------------------------
      - name: 5. Upload Artifact (.deb package)
        uses: actions/upload-artifact@v4
        with:
          name: Tweak-Package
          path: ./packages/*.deb
          if-no-files-found: error

