name: Build Tweak (Refactored)

on:
  push:
    branches:
      - main
      - 'feature/toggleable-search-ui-removal'
  workflow_dispatch:

jobs:
  build-and-package:
    name: Compile and Package .deb
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. 安装 Theos
      - name: Install Theos
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential curl
          git clone --recursive https://github.com/theos/theos $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      # 3. 调试：列出文件
      - name: Debug – List Files
        run: |
          echo "--- Repository Files ---"
          ls -la
          echo "--- Makefile Preview ---"
          head -50 Makefile

      # 4. 编译 & 打包
      - name: Build and Package
        run: |
          make clean
          make package FINALPACKAGE=1

      # 5. 上传编译产物
      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DYYY-Tweak-Package
          path: ./packages/**/*.deb
          if-no-files-found: warn