name: Build Tweak

on:
  push:
    branches:
      - 'feature/toggleable-search-ui-removal'
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git perl fakeroot dpkg lzma unzip curl

      - name: Clone Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git "$HOME/theos"
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      # ✅ 新增：安装交叉编译工具链
      - name: Install iOS Cross Toolchain
        run: |
          mkdir -p "$HOME/theos/toolchain/linux"
          git clone --depth=1 https://github.com/theos/toolchain-linux.git "$HOME/theos/toolchain/linux/iphone"

      - name: Download iOS 16.1 SDK
        run: |
          mkdir -p "$HOME/theos/sdks"
          curl -L -o iPhoneOS16.1.sdk.zip \
            https://github.com/xybp888/iOS-SDKs/releases/download/iOS-SDKs/iPhoneOS16.1.sdk.zip
          unzip -o iPhoneOS16.1.sdk.zip -d "$HOME/theos/sdks/"
          rm iPhoneOS16.1.sdk.zip

      - name: Build and Package Tweak
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Upload .deb Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lemon-Tweak-deb
          path: ./packages/*.deb
          if-no-files-found: error